name: Github Pages
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build Vue
        steps:
        - uses: actions/checkout@v2
        - uses: xRealNeon/VuePagesAction@1.0.1
          with:
            username: 'olcpp'
            reponame: 'olcpp.github.io'
            token: ${{ secrets.TOKEN }}